### ISSUE TITLE
Authorization help

### ISSUE THREAD

**Issue by akelder** [jroehl/google-sheet-cli#287]
Hello,

Really basic question here. When I run the tool:

```
$ google-sheet spreadsheet:get --spreadsheetId=xyz
```

I get prompted for:

```
What is your client email?: ***********************
What is your private key?: 
```

Is it asking for a SSH type private key? Where in Google Apps do I authorize my private key to access the spreadsheet?

Thanks,
Alain

**Comment by georgettica** [comment]
I tried to pull SA json credential and passed the `private_key` but this didn't work

**Comment by jroehl** [comment]
Thank you for your feedback. I updated the documentation to include the information that you need. https://github.com/jroehl/google-sheet-cli#how-to-configure.
